<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doccer\Doccer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Fixtures\*.jsonl" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
