<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Doccer.TestRunner.FakeChild</AssemblyName>
    <RootNamespace>Doccer.TestRunner.FakeChild</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Doccer.TestRunner.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Doccer.TestRunner\Doccer.TestRunner.csproj" />
  </ItemGroup>
</Project>
